# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "devise-certificate"
	s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
	s.authors = ["Authy Inc.", "Daniël W. Crompton"]
  s.date = "2014-03-13"
  s.description = "Cerfificate plugin for Devise"
	s.email = "devise+certificate@specialbrands.net"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/assets/javascripts/devise_certificate.js",
    "app/assets/stylesheets/devise_certificate.css",
    "app/assets/stylesheets/devise_certificate.sass",
    "app/controllers/devise/devise_certificate_controller.rb",
    "app/views/devise/enable_certificate.html.erb",
    "app/views/devise/enable_certificate.html.haml",
    "app/views/devise/verify_certificate.html.erb",
    "app/views/devise/verify_certificate.html.haml",
    "app/views/devise/verify_certificate_installation.html.erb",
    "app/views/devise/verify_certificate_installation.html.haml",
    "certificate-devise-demo/.gitignore",
    "certificate-devise-demo/Gemfile",
    "certificate-devise-demo/Gemfile.lock",
    "certificate-devise-demo/README.md",
    "certificate-devise-demo/Rakefile",
    "certificate-devise-demo/app/assets/images/rails.png",
    "certificate-devise-demo/app/assets/javascripts/application.js",
    "certificate-devise-demo/app/assets/javascripts/devise_certificate.js",
    "certificate-devise-demo/app/assets/javascripts/welcome.js.coffee",
    "certificate-devise-demo/app/assets/stylesheets/application.css",
    "certificate-devise-demo/app/assets/stylesheets/devise_certificate.css",
    "certificate-devise-demo/app/assets/stylesheets/welcome.css.scss",
    "certificate-devise-demo/app/controllers/application_controller.rb",
    "certificate-devise-demo/app/controllers/welcome_controller.rb",
    "certificate-devise-demo/app/helpers/application_helper.rb",
    "certificate-devise-demo/app/helpers/welcome_helper.rb",
    "certificate-devise-demo/app/mailers/.gitkeep",
    "certificate-devise-demo/app/models/.gitkeep",
    "certificate-devise-demo/app/models/user.rb",
    "certificate-devise-demo/app/views/devise/devise_certificate/enable_certificate.html.erb",
    "certificate-devise-demo/app/views/devise/devise_certificate/verify_certificate.html.erb",
    "certificate-devise-demo/app/views/devise/devise_certificate/verify_certificate_installation.html.erb",
    "certificate-devise-demo/app/views/layouts/application.html.erb",
    "certificate-devise-demo/app/views/welcome/index.html.erb",
    "certificate-devise-demo/config.ru",
    "certificate-devise-demo/config/application.rb",
    "certificate-devise-demo/config/boot.rb",
    "certificate-devise-demo/config/database.yml",
    "certificate-devise-demo/config/environment.rb",
    "certificate-devise-demo/config/environments/development.rb",
    "certificate-devise-demo/config/environments/production.rb",
    "certificate-devise-demo/config/environments/test.rb",
    "certificate-devise-demo/config/initializers/certificate.rb",
    "certificate-devise-demo/config/initializers/backtrace_silencers.rb",
    "certificate-devise-demo/config/initializers/devise.rb",
    "certificate-devise-demo/config/initializers/inflections.rb",
    "certificate-devise-demo/config/initializers/mime_types.rb",
    "certificate-devise-demo/config/initializers/secret_token.rb",
    "certificate-devise-demo/config/initializers/session_store.rb",
    "certificate-devise-demo/config/initializers/wrap_parameters.rb",
    "certificate-devise-demo/config/locales/devise.certificate.en.yml",
    "certificate-devise-demo/config/locales/devise.en.yml",
    "certificate-devise-demo/config/locales/en.yml",
    "certificate-devise-demo/config/routes.rb",
    "certificate-devise-demo/db/migrate/20130409234357_devise_create_users.rb",
    "certificate-devise-demo/db/schema.rb",
    "certificate-devise-demo/db/seeds.rb",
    "certificate-devise-demo/lib/assets/.gitkeep",
    "certificate-devise-demo/lib/tasks/.gitkeep",
    "certificate-devise-demo/log/.gitkeep",
    "certificate-devise-demo/public/404.html",
    "certificate-devise-demo/public/422.html",
    "certificate-devise-demo/public/500.html",
    "certificate-devise-demo/public/favicon.ico",
    "certificate-devise-demo/public/robots.txt",
    "certificate-devise-demo/script/rails",
    "certificate-devise-demo/test/fixtures/.gitkeep",
    "certificate-devise-demo/test/fixtures/users.yml",
    "certificate-devise-demo/test/functional/.gitkeep",
    "certificate-devise-demo/test/functional/welcome_controller_test.rb",
    "certificate-devise-demo/test/integration/.gitkeep",
    "certificate-devise-demo/test/performance/browsing_test.rb",
    "certificate-devise-demo/test/test_helper.rb",
    "certificate-devise-demo/test/unit/.gitkeep",
    "certificate-devise-demo/test/unit/helpers/welcome_helper_test.rb",
    "certificate-devise-demo/test/unit/user_test.rb",
    "certificate-devise-demo/vendor/assets/javascripts/.gitkeep",
    "certificate-devise-demo/vendor/assets/stylesheets/.gitkeep",
    "certificate-devise-demo/vendor/plugins/.gitkeep",
    "config/locales/en.yml",
    "devise-certificate.gemspec",
    "lib/devise-certificate.rb",
    "lib/devise-certificate/controllers/helpers.rb",
    "lib/devise-certificate/controllers/view_helpers.rb",
    "lib/devise-certificate/hooks/certificate_authenticatable.rb",
    "lib/devise-certificate/models/certificate_authenticatable.rb",
    "lib/devise-certificate/rails.rb",
    "lib/devise-certificate/routes.rb",
    "lib/generators/active_record/devise_certificate_generator.rb",
    "lib/generators/active_record/templates/migration.rb",
    "lib/generators/devise_certificate/devise_certificate_generator.rb",
    "lib/generators/devise_certificate/install_generator.rb",
    "spec/controllers/devise_certificate_controller_spec.rb",
    "spec/features/certificate_authenticatable_spec.rb",
    "spec/generators_spec.rb",
    "spec/models/certificate_authenticatable.rb",
    "spec/orm/active_record.rb",
    "spec/rails-app/Gemfile",
    "spec/rails-app/Gemfile.lock",
    "spec/rails-app/Rakefile",
    "spec/rails-app/app/assets/images/rails.png",
    "spec/rails-app/app/assets/javascripts/application.js",
    "spec/rails-app/app/assets/javascripts/devise_certificate.js",
    "spec/rails-app/app/assets/javascripts/welcome.js",
    "spec/rails-app/app/assets/stylesheets/application.css",
    "spec/rails-app/app/assets/stylesheets/devise_certificate.css",
    "spec/rails-app/app/assets/stylesheets/welcome.css.scss",
    "spec/rails-app/app/controllers/application_controller.rb",
    "spec/rails-app/app/controllers/welcome_controller.rb",
    "spec/rails-app/app/helpers/application_helper.rb",
    "spec/rails-app/app/helpers/welcome_helper.rb",
    "spec/rails-app/app/mailers/.gitkeep",
    "spec/rails-app/app/models/.gitkeep",
    "spec/rails-app/app/models/user.rb",
    "spec/rails-app/app/views/devise/devise_certificate/enable_certificate.html.erb",
    "spec/rails-app/app/views/devise/devise_certificate/verify_certificate.html.erb",
    "spec/rails-app/app/views/devise/devise_certificate/verify_certificate_installation.html.erb",
    "spec/rails-app/app/views/layouts/application.html.erb",
    "spec/rails-app/app/views/welcome/index.html.erb",
    "spec/rails-app/config.ru",
    "spec/rails-app/config/application.rb",
    "spec/rails-app/config/boot.rb",
    "spec/rails-app/config/database.yml",
    "spec/rails-app/config/environment.rb",
    "spec/rails-app/config/environments/development.rb",
    "spec/rails-app/config/environments/production.rb",
    "spec/rails-app/config/environments/test.rb",
    "spec/rails-app/config/initializers/certificate.rb",
    "spec/rails-app/config/initializers/backtrace_silencers.rb",
    "spec/rails-app/config/initializers/devise.rb",
    "spec/rails-app/config/initializers/inflections.rb",
    "spec/rails-app/config/initializers/mime_types.rb",
    "spec/rails-app/config/initializers/secret_token.rb",
    "spec/rails-app/config/initializers/session_store.rb",
    "spec/rails-app/config/initializers/wrap_parameters.rb",
    "spec/rails-app/config/locales/devise.certificate.en.yml",
    "spec/rails-app/config/locales/devise.en.yml",
    "spec/rails-app/config/locales/en.yml",
    "spec/rails-app/config/routes.rb",
    "spec/rails-app/db/development.sqlite3",
    "spec/rails-app/db/migrate/20130419164907_devise_create_users.rb",
    "spec/rails-app/db/schema.rb",
    "spec/rails-app/db/seeds.rb",
    "spec/rails-app/lib/assets/.gitkeep",
    "spec/rails-app/lib/tasks/.gitkeep",
    "spec/rails-app/public/404.html",
    "spec/rails-app/public/422.html",
    "spec/rails-app/public/500.html",
    "spec/rails-app/public/favicon.ico",
    "spec/rails-app/public/robots.txt",
    "spec/rails-app/script/rails",
    "spec/routing/routes_spec.rb",
    "spec/spec_helper.rb",
    "spec/support/helpers.rb"
  ]
  s.homepage = "https://github.com/SpecialBrands/certificate-devise"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Certificate plugin for Devise"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_development_dependency(%q<sass-rails>, [">= 0"])
      s.add_development_dependency(%q<jquery-rails>, [">= 0"])
      s.add_development_dependency(%q<pry>, [">= 0"])
    else
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<rdoc>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<sass-rails>, [">= 0"])
      s.add_dependency(%q<jquery-rails>, [">= 0"])
      s.add_dependency(%q<pry>, [">= 0"])
    end
  else
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<rdoc>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<sass-rails>, [">= 0"])
    s.add_dependency(%q<jquery-rails>, [">= 0"])
    s.add_dependency(%q<pry>, [">= 0"])
  end
end

