source "https://rubygems.org"

gem "rails", "~> 4.2.7"
gem 'json', '>= 1.8.1'
gem 'sqlite3', '~> 1.3', '< 1.4'
gem "rake"
gem "authy"
gem "devise", '>= 3.0.0'
gem "devise-authy", :path => "../.."
gem 'launchy'
